import type { NextApiRequest, NextApiResponse } from 'next';
import type { Product } from '../../core/product';

export default async function handler(
   req: NextApiRequest,
   res: NextApiResponse
) {
   const names: string[] = [
      'Aaran',
      'Aaren',
      'Aarez',
      'Aarman',
      'Aaron',
      'Aaron-James',
      'Aarron',
      'Aaryan',
      'Aaryn',
      'Aayan',
      'Aazaan',
      'Abaan',
      'Abbas',
      'Abdallah',
      'Abdalroof',
      'Abdihakim',
      'Abdirahman',
      'Abdisalam',
      'Abdul',
      'Abdul-Aziz',
      'Abdulbasir',
      'Abdulkadir',
      'Abdulkarem',
      'Abdulkhader',
      'Abdullah',
      'Abdul-Majeed',
      'Abdulmalik',
      'Abdul-Rehman',
      'Abdur',
      'Abdurraheem',
      'Abdur-Rahman',
      'Abdur-Rehmaan',
      'Abel',
      'Abhinav',
      'Abhisumant',
      'Abid',
      'Abir',
      'Abraham',
      'Abu',
      'Abubakar',
      'Ace',
      'Adain',
      'Adam',
      'Adam-James',
      'Addison',
      'Addisson',
      'Adegbola',
      'Adegbolahan',
      'Aden',
      'Adenn',
      'Adie',
      'Adil',
      'Aditya',
      'Adnan',
      'Adrian',
      'Adrien',
      'Aedan',
      'Aedin',
      'Aedyn',
      'Aeron',
      'Afonso',
      'Ahmad',
      'Ahmed',
      'Ahmed-Aziz',
      'Ahoua',
      'Ahtasham',
      'Aiadan',
      'Aidan',
      'Aiden',
      'Aiden-Jack',
      'Aiden-Vee',
      'Aidian',
      'Aidy',
      'Ailin',
      'Aiman',
      'Ainsley',
      'Ainslie',
      'Airen',
      'Airidas',
      'Airlie',
      'AJ',
      'Ajay',
      'A-Jay',
      'Ajayraj',
      'Akan',
      'Akram',
      'Al',
      'Ala',
      'Alan',
      'Alanas',
      'Alasdair',
      'Alastair',
      'Alber',
      'Albert',
      'Albie',
      'Aldred',
      'Alec',
      'Aled',
      'Aleem',
      'Aleksandar',
      'Aleksander',
      'Aleksandr',
      'Aleksandrs',
      'Alekzander',
      'Alessandro',
      'Alessio',
      'Alex',
      'Alexander',
      'Alexei',
      'Alexx',
      'Alexzander',
      'Alf',
      'Alfee',
      'Alfie',
      'Alfred',
      'Alfy',
      'Alhaji',
      'Al-Hassan',
      'Ali',
      'Aliekber',
      'Alieu',
      'Alihaider',
      'Alisdair',
      'Alishan',
      'Alistair',
      'Alistar',
      'Alister',
      'Aliyaan',
      'Allan',
      'Allan-Laiton',
      'Allen',
      'Allesandro',
      'Allister',
      'Ally',
      'Alphonse',
      'Altyiab',
      'Alum',
      'Alvern',
      'Alvin',
      'Alyas',
      'Amaan',
      'Aman',
      'Amani',
      'Ambanimoh',
      'Ameer',
      'Amgad',
      'Ami',
      'Amin',
      'Amir',
      'Ammaar',
      'Ammar',
      'Ammer',
      'Amolpreet',
      'Amos',
      'Amrinder',
      'Amrit',
      'Amro',
      'Anay',
      'Andrea',
      'Andreas',
      'Andrei',
      'Andrejs',
      'Andrew',
      'Andy',
      'Anees',
      'Anesu',
      'Angel',
      'Angelo',
      'Angus',
      'Anir',
      'Anis',
      'Anish',
      'Anmolpreet',
      'Annan',
      'Anndra',
      'Anselm',
      'Anthony',
      'Anthony-John',
      'Antoine',
      'Anton',
      'Antoni',
      'Antonio',
      'Antony',
      'Antonyo',
      'Anubhav',
      'Aodhan',
      'Aon',
      'Aonghus',
      'Apisai',
      'Arafat',
      'Aran',
      'Arandeep',
      'Arann',
      'Aray',
      'Arayan',
      'Archibald',
      'Archie',
      'Arda',
      'Ardal',
      'Ardeshir',
      'Areeb',
      'Areez',
      'Aref',
      'Arfin',
      'Argyle',
      'Argyll',
      'Ari',
      'Aria',
      'Arian',
      'Arihant',
      'Aristomenis',
      'Aristotelis',
      'Arjuna',
      'Arlo',
      'Armaan',
      'Arman',
      'Armen',
      'Arnab',
      'Arnav',
      'Arnold',
      'Aron',
      'Aronas',
      'Arran',
      'Arrham',
      'Arron',
      'Arryn',
      'Arsalan',
      'Artem',
      'Arthur',
      'Artur',
      'Arturo',
      'Arun',
      'Arunas',
      'Arved',
      'Arya',
      'Aryan',
      'Aryankhan',
      'Aryian',
      'Aryn',
      'Asa',
      'Asfhan',
      'Ash',
      'Ashlee-jay',
      'Ashley',
      'Ashton',
      'Ashton-Lloyd',
      'Ashtyn',
      'Ashwin',
      'Asif',
      'Asim',
      'Aslam',
      'Asrar',
      'Ata',
      'Atal',
      'Atapattu',
      'Ateeq',
      'Athol',
      'Athon',
      'Athos-Carlos',
      'Atli',
      'Atom',
      'Attila',
      'Aulay',
      'Aun',
      'Austen',
      'Austin',
      'Avani',
      'Averon',
      'Avi',
      'Avinash',
      'Avraham',
      'Awais',
      'Awwal',
      'Axel',
      'Ayaan',
      'Ayan',
      'Aydan',
      'Ayden',
      'Aydin',
      'Aydon',
      'Ayman',
      'Ayomide',
      'Ayren',
      'Ayrton',
      'Aytug',
      'Ayub',
      'Ayyub',
      'Azaan',
      'Azedine',
      'Azeem',
      'Azim',
      'Aziz',
      'Azlan',
      'Azzam',
      'Azzedine',
      'Babatunmise',
      'Babur',
      'Bader',
      'Badr',
      'Badsha',
      'Bailee',
      'Bailey',
      'Bailie',
      'Bailley',
      'Baillie',
      'Baley',
      'Balian',
      'Banan',
      'Barath',
      'Barkley',
      'Barney',
      'Baron',
      'Barrie',
      'Barry',
      'Bartlomiej',
      'Bartosz',
      'Basher',
      'Basile',
      'Baxter',
      'Baye',
      'Bayley',
      'Beau',
      'Beinn',
      'Bekim',
      'Believe',
      'Ben',
      'Bendeguz',
      'Benedict',
      'Benjamin',
      'Benjamyn',
      'Benji',
      'Benn',
      'Bennett',
      'Benny',
      'Benoit',
      'Bentley',
      'Berkay',
      'Bernard',
      'Bertie',
      'Bevin',
      'Bezalel',
      'Bhaaldeen',
      'Bharath',
      'Bilal',
      'Bill',
      'Billy',
      'Binod',
      'Bjorn',
      'Blaike',
      'Blaine',
      'Blair',
      'Blaire',
      'Blake',
      'Blazej',
      'Blazey',
      'Blessing',
      'Blue',
      'Blyth',
      'Bo',
      'Boab',
      'Bob',
      'Bobby',
      'Bobby-Lee',
      'Bodhan',
      'Boedyn',
      'Bogdan',
      'Bohbi',
      'Bony',
      'Bowen',
      'Bowie',
      'Boyd',
      'Bracken',
      'Brad',
      'Bradan',
      'Braden',
      'Bradley',
      'Bradlie',
      'Bradly',
      'Brady',
      'Bradyn',
      'Braeden',
      'Braiden',
      'Brajan',
      'Brandan',
      'Branden',
      'Brandon',
      'Brandonlee',
      'Brandon-Lee',
      'Brandyn',
      'Brannan',
      'Brayden',
      'Braydon',
      'Braydyn',
      'Breandan',
      'Brehme',
      'Brendan',
      'Brendon',
      'Brendyn',
      'Breogan',
      'Bret',
      'Brett',
      'Briaddon',
      'Brian',
      'Brodi',
      'Brodie',
      'Brody',
      'Brogan',
      'Broghan',
      'Brooke',
      'Brooklin',
      'Brooklyn',
      'Bruce',
      'Bruin',
      'Bruno',
      'Brunon',
      'Bryan',
      'Bryce',
      'Bryden',
      'Brydon',
      'Brydon-Craig',
      'Bryn',
      'Brynmor',
      'Bryson',
      'Buddy',
      'Bully',
      'Burak',
      'Burhan',
      'Butali',
      'Butchi',
      'Byron',
      'Cabhan',
      'Cadan',
      'Cade',
      'Caden',
      'Cadon',
      'Cadyn',
      'Caedan',
      'Caedyn',
      'Cael',
      'Caelan',
      'Caelen',
      'Caethan',
      'Cahl',
      'Cahlum',
      'Cai',
      'Caidan',
      'Caiden',
      'Caiden-Paul',
      'Caidyn',
      'Caie',
      'Cailaen',
      'Cailean',
      'Caileb-John',
      'Cailin',
      'Cain',
      'Caine',
      'Cairn',
      'Cal',
      'Calan',
      'Calder',
      'Cale',
      'Calean',
      'Caleb',
      'Calen',
      'Caley',
      'Calib',
      'Calin',
      'Callahan',
      'Callan',
      'Callan-Adam',
      'Calley',
      'Callie',
      'Callin',
      'Callum',
      'Callun',
      'Callyn',
      'Calum',
      'Calum-James',
      'Calvin',
      'Cambell',
      'Camerin',
      'Cameron',
      'Campbel',
      'Campbell',
      'Camron',
      'Caolain',
      'Caolan',
      'Carl',
      'Carlo',
      'Carlos',
      'Carrich',
      'Carrick',
      'Carson',
      'Carter',
      'Carwyn',
      'Casey',
      'Casper',
      'Cassy',
      'Cathal',
      'Cator',
      'Cavan',
      'Cayden',
      'Cayden-Robert',
      'Cayden-Tiamo',
      'Ceejay',
      'Ceilan',
      'Ceiran',
      'Ceirin',
      'Ceiron',
      'Cejay',
      'Celik',
      'Cephas',
      'Cesar',
      'Cesare',
      'Chad',
      'Chaitanya',
      'Chang-Ha',
      'Charles',
      'Charley',
      'Charlie',
      'Charly',
      'Chase',
      'Che',
      'Chester',
      'Chevy',
      'Chi',
      'Chibudom',
      'Chidera',
      'Chimsom',
      'Chin',
      'Chintu',
      'Chiqal',
      'Chiron',
      'Chris',
      'Chris-Daniel',
      'Chrismedi',
      'Christian',
      'Christie',
      'Christoph',
      'Christopher',
      'Christopher-Lee',
      'Christy',
      'Chu',
      'Chukwuemeka',
      'Cian',
      'Ciann',
      'Ciar',
      'Ciaran',
      'Ciarian',
      'Cieran',
      'Cillian',
      'Cillin',
      'Cinar',
      'CJ',
      'C-Jay',
      'Clark',
      'Clarke',
      'Clayton',
      'Clement',
      'Clifford',
      'Clyde',
      'Cobain',
      'Coban',
      'Coben',
      'Cobi',
      'Cobie',
      'Coby',
      'Codey',
      'Codi',
      'Codie',
      'Cody',
      'Cody-Lee',
      'Coel',
      'Cohan',
      'Cohen',
      'Colby',
      'Cole',
      'Colin',
      'Coll',
      'Colm',
      'Colt',
      'Colton',
      'Colum',
      'Colvin',
      'Comghan',
      'Conal',
      'Conall',
      'Conan',
      'Conar',
      'Conghaile',
      'Conlan',
      'Conley',
      'Conli',
      'Conlin',
      'Conlly',
      'Conlon',
      'Conlyn',
      'Connal',
      'Connall',
      'Connan',
      'Connar',
      'Connel',
      'Connell',
      'Conner',
      'Connolly',
      'Connor',
      'Connor-David',
      'Conor',
      'Conrad',
      'Cooper',
      'Copeland',
      'Coray',
      'Corben',
      'Corbin',
      'Corey',
      'Corey-James',
      'Corey-Jay',
      'Cori',
      'Corie',
      'Corin',
      'Cormac',
      'Cormack',
      'Cormak',
      'Corran',
      'Corrie',
      'Cory',
      'Cosmo',
      'Coupar',
      'Craig',
      'Craig-James',
      'Crawford',
      'Creag',
      'Crispin',
      'Cristian',
      'Crombie',
      'Cruiz',
      'Cruz',
      'Cuillin',
      'Cullen',
      'Cullin',
      'Curtis',
      'Cyrus',
      'Daanyaal',
      'Daegan',
      'Daegyu',
      'Dafydd',
      'Dagon',
      'Dailey',
      'Daimhin',
      'Daithi',
      'Dakota',
      'Daksh',
      'Dale',
      'Dalong',
      'Dalton',
      'Damian',
      'Damien',
      'Damon',
      'Dan',
      'Danar',
      'Dane',
      'Danial',
      'Daniel',
      'Daniele',
      'Daniel-James',
      'Daniels',
      'Daniil',
      'Danish',
      'Daniyal',
      'Danniel',
      'Danny',
      'Dante',
      'Danyal',
      'Danyil',
      'Danys',
      'Daood',
      'Dara',
      'Darach',
      'Daragh',
      'Darcy',
      "D'arcy",
      'Dareh',
      'Daren',
      'Darien',
      'Darius',
      'Darl',
      'Darn',
      'Darrach',
      'Darragh',
      'Darrel',
      'Darrell',
      'Darren',
      'Darrie',
      'Darrius',
      'Darroch',
      'Darryl',
      'Darryn',
      'Darwyn',
      'Daryl',
      'Daryn',
      'Daud',
      'Daumantas',
      'Davi',
      'David',
      'David-Jay',
      'David-Lee',
      'Davie',
      'Davis',
      'Davy',
      'Dawid',
      'Dawson',
      'Dawud',
      'Dayem',
      'Daymian',
      'Deacon',
      'Deagan',
      'Dean',
      'Deano',
      'Decklan',
      'Declain',
      'Declan',
      'Declyan',
      'Declyn',
      'Dedeniseoluwa',
      'Deecan',
      'Deegan',
      'Deelan',
      'Deklain-Jaimes',
      'Del',
      'Demetrius',
      'Denis',
      'Deniss',
      'Dennan',
      'Dennin',
      'Dennis',
      'Denny',
      'Dennys',
      'Denon',
      'Denton',
      'Denver',
      'Denzel',
      'Deon',
      'Derek',
      'Derick',
      'Derin',
      'Dermot',
      'Derren',
      'Derrie',
      'Derrin',
      'Derron',
      'Derry',
      'Derryn',
      'Deryn',
      'Deshawn',
      'Desmond',
      'Dev',
      'Devan',
      'Devin',
      'Devlin',
      'Devlyn',
      'Devon',
      'Devrin',
      'Devyn',
      'Dex',
      'Dexter',
      'Dhani',
      'Dharam',
      'Dhavid',
      'Dhyia',
      'Diarmaid',
      'Diarmid',
      'Diarmuid',
      'Didier',
      'Diego',
      'Diesel',
      'Diesil',
      'Digby',
      'Dilan',
      'Dilano',
      'Dillan',
      'Dillon',
      'Dilraj',
      'Dimitri',
      'Dinaras',
      'Dion',
      'Dissanayake',
      'Dmitri',
      'Doire',
      'Dolan',
      'Domanic',
      'Domenico',
      'Domhnall',
      'Dominic',
      'Dominick',
      'Dominik',
      'Donald',
      'Donnacha',
      'Donnie',
      'Dorian',
      'Dougal',
      'Douglas',
      'Dougray',
      'Drakeo',
      'Dre',
      'Dregan',
      'Drew',
      'Dugald',
      'Duncan',
      'Duriel',
      'Dustin',
      'Dylan',
      'Dylan-Jack',
      'Dylan-James',
      'Dylan-John',
      'Dylan-Patrick',
      'Dylin',
      'Dyllan',
      'Dyllan-James',
      'Dyllon',
      'Eadie',
      'Eagann',
      'Eamon',
      'Eamonn',
      'Eason',
      'Eassan',
      'Easton',
      'Ebow',
      'Ed',
      'Eddie',
      'Eden',
      'Ediomi',
      'Edison',
      'Eduardo',
      'Eduards',
      'Edward',
      'Edwin',
      'Edwyn',
      'Eesa',
      'Efan',
      'Efe',
      'Ege',
      'Ehsan',
      'Ehsen',
      'Eiddon',
      'Eidhan',
      'Eihli',
      'Eimantas',
      'Eisa',
      'Eli',
      'Elias',
      'Elijah',
      'Eliot',
      'Elisau',
      'Eljay',
      'Eljon',
      'Elliot',
      'Elliott',
      'Ellis',
      'Ellisandro',
      'Elshan',
      'Elvin',
      'Elyan',
      'Emanuel',
      'Emerson',
      'Emil',
      'Emile',
      'Emir',
      'Emlyn',
      'Emmanuel',
      'Emmet',
      'Eng',
      'Eniola',
      'Enis',
      'Ennis',
      'Enrico',
      'Enrique',
      'Enzo',
      'Eoghain',
      'Eoghan',
      'Eoin',
      'Eonan',
      'Erdehan',
      'Eren',
      'Erencem',
      'Eric',
      'Ericlee',
      'Erik',
      'Eriz',
      'Ernie-Jacks',
      'Eroni',
      'Eryk',
      'Eshan',
      'Essa',
      'Esteban',
      'Ethan',
      'Etienne',
      'Etinosa',
      'Euan',
      'Eugene',
      'Evan',
      'Evann',
      'Ewan',
      'Ewen',
      'Ewing',
      'Exodi',
      'Ezekiel',
      'Ezra',
      'Fabian',
      'Fahad',
      'Faheem',
      'Faisal',
      'Faizaan',
      'Famara',
      'Fares',
      'Farhaan',
      'Farhan',
      'Farren',
      'Farzad',
      'Fauzaan',
      'Favour',
      'Fawaz',
      'Fawkes',
      'Faysal',
      'Fearghus',
      'Feden',
      'Felix',
      'Fergal',
      'Fergie',
      'Fergus',
      'Ferre',
      'Fezaan',
      'Fiachra',
      'Fikret',
      'Filip',
      'Filippo',
      'Finan',
      'Findlay',
      'Findlay-James',
      'Findlie',
      'Finlay',
      'Finley',
      'Finn',
      'Finnan',
      'Finnean',
      'Finnen',
      'Finnlay',
      'Finnley',
      'Fintan',
      'Fionn',
      'Firaaz',
      'Fletcher',
      'Flint',
      'Florin',
      'Flyn',
      'Flynn',
      'Fodeba',
      'Folarinwa',
      'Forbes',
      'Forgan',
      'Forrest',
      'Fox',
      'Francesco',
      'Francis',
      'Francisco',
      'Franciszek',
      'Franco',
      'Frank',
      'Frankie',
      'Franklin',
      'Franko',
      'Fraser',
      'Frazer',
      'Fred',
      'Freddie',
      'Frederick',
      'Fruin',
      'Fyfe',
      'Fyn',
      'Fynlay',
      'Fynn',
      'Gabriel',
      'Gallagher',
      'Gareth',
      'Garren',
      'Garrett',
      'Garry',
      'Gary',
      'Gavin',
      'Gavin-Lee',
      'Gene',
      'Geoff',
      'Geoffrey',
      'Geomer',
      'Geordan',
      'Geordie',
      'George',
      'Georgia',
      'Georgy',
      'Gerard',
      'Ghyll',
      'Giacomo',
      'Gian',
      'Giancarlo',
      'Gianluca',
      'Gianmarco',
      'Gideon',
      'Gil',
      'Gio',
      'Girijan',
      'Girius',
      'Gjan',
      'Glascott',
      'Glen',
      'Glenn',
      'Gordon',
      'Grady',
      'Graeme',
      'Graham',
      'Grahame',
      'Grant',
      'Grayson',
      'Greg',
      'Gregor',
      'Gregory',
      'Greig',
      'Griffin',
      'Griffyn',
      'Grzegorz',
      'Guang',
      'Guerin',
      'Guillaume',
      'Gurardass',
      'Gurdeep',
      'Gursees',
      'Gurthar',
      'Gurveer',
      'Gurwinder',
      'Gus',
      'Gustav',
      'Guthrie',
      'Guy',
      'Gytis',
      'Habeeb',
      'Hadji',
      'Hadyn',
      'Hagun',
      'Haiden',
      'Haider',
      'Hamad',
      'Hamid',
      'Hamish',
      'Hamza',
      'Hamzah',
      'Han',
      'Hansen',
      'Hao',
      'Hareem',
      'Hari',
      'Harikrishna',
      'Haris',
      'Harish',
      'Harjeevan',
      'Harjyot',
      'Harlee',
      'Harleigh',
      'Harley',
      'Harman',
      'Harnek',
      'Harold',
      'Haroon',
      'Harper',
      'Harri',
      'Harrington',
      'Harris',
      'Harrison',
      'Harry',
      'Harvey',
      'Harvie',
      'Harvinder',
      'Hasan',
      'Haseeb',
      'Hashem',
      'Hashim',
      'Hassan',
      'Hassanali',
      'Hately',
      'Havila',
      'Hayden',
      'Haydn',
      'Haydon',
      'Haydyn',
      'Hcen',
      'Hector',
      'Heddle',
      'Heidar',
      'Heini',
      'Hendri',
      'Henri',
      'Henry',
      'Herbert',
      'Heyden',
      'Hiro',
      'Hirvaansh',
      'Hishaam',
      'Hogan',
      'Honey',
      'Hong',
      'Hope',
      'Hopkin',
      'Hosea',
      'Howard',
      'Howie',
      'Hristomir',
      'Hubert',
      'Hugh',
      'Hugo',
      'Humza',
      'Hunter',
      'Husnain',
      'Hussain',
      'Hussan',
      'Hussnain',
      'Hussnan',
      'Hyden',
      'I',
      'Iagan',
      'Iain',
      'Ian',
      'Ibraheem',
      'Ibrahim',
      'Idahosa',
      'Idrees',
      'Idris',
      'Iestyn',
      'Ieuan',
      'Igor',
      'Ihtisham',
      'Ijay',
      'Ikechukwu',
      'Ikemsinachukwu',
      'Ilyaas',
      'Ilyas',
      'Iman',
      'Immanuel',
      'Inan',
      'Indy',
      'Ines',
      'Innes',
      'Ioannis',
      'Ireayomide',
      'Ireoluwa',
      'Irvin',
      'Irvine',
      'Isa',
      'Isaa',
      'Isaac',
      'Isaiah',
      'Isak',
      'Isher',
      'Ishwar',
      'Isimeli',
      'Isira',
      'Ismaeel',
      'Ismail',
      'Israel',
      'Issiaka',
      'Ivan',
      'Ivar',
      'Izaak',
      'J',
      'Jaay',
      'Jac',
      'Jace',
      'Jack',
      'Jacki',
      'Jackie',
      'Jack-James',
      'Jackson',
      'Jacky',
      'Jacob',
      'Jacques',
      'Jad',
      'Jaden',
      'Jadon',
      'Jadyn',
      'Jae',
      'Jagat',
      'Jago',
      'Jaheim',
      'Jahid',
      'Jahy',
      'Jai',
      'Jaida',
      'Jaiden',
      'Jaidyn',
      'Jaii',
      'Jaime',
      'Jai-Rajaram',
      'Jaise',
      'Jak',
      'Jake',
      'Jakey',
      'Jakob',
      'Jaksyn',
      'Jakub',
      'Jamaal',
      'Jamal',
      'Jameel',
      'Jameil',
      'James',
      'James-Paul',
      'Jamey',
      'Jamie',
      'Jan',
      'Jaosha',
      'Jardine',
      'Jared',
      'Jarell',
      'Jarl',
      'Jarno',
      'Jarred',
      'Jarvi',
      'Jasey-Jay',
      'Jasim',
      'Jaskaran',
      'Jason',
      'Jasper',
      'Jaxon',
      'Jaxson',
      'Jay',
      'Jaydan',
      'Jayden',
      'Jayden-James',
      'Jayden-Lee',
      'Jayden-Paul',
      'Jayden-Thomas',
      'Jaydn',
      'Jaydon',
      'Jaydyn',
      'Jayhan',
      'Jay-Jay',
      'Jayke',
      'Jaymie',
      'Jayse',
      'Jayson',
      'Jaz',
      'Jazeb',
      'Jazib',
      'Jazz',
      'Jean',
      'Jean-Lewis',
      'Jean-Pierre',
      'Jebadiah',
      'Jed',
      'Jedd',
      'Jedidiah',
      'Jeemie',
      'Jeevan',
      'Jeffrey',
      'Jensen',
      'Jenson',
      'Jensyn',
      'Jeremy',
      'Jerome',
      'Jeronimo',
      'Jerrick',
      'Jerry',
      'Jesse',
      'Jesuseun',
      'Jeswin',
      'Jevan',
      'Jeyun',
      'Jez',
      'Jia',
      'Jian',
      'Jiao',
      'Jimmy',
      'Jincheng',
      'JJ',
      'Joaquin',
      'Joash',
      'Jock',
      'Jody',
      'Joe',
      'Joeddy',
      'Joel',
      'Joey',
      'Joey-Jack',
      'Johann',
      'Johannes',
      'Johansson',
      'John',
      'Johnathan',
      'Johndean',
      'Johnjay',
      'John-Michael',
      'Johnnie',
      'Johnny',
      'Johnpaul',
      'John-Paul',
      'John-Scott',
      'Johnson',
      'Jole',
      'Jomuel',
      'Jon',
      'Jonah',
      'Jonatan',
      'Jonathan',
      'Jonathon',
      'Jonny',
      'Jonothan',
      'Jon-Paul',
      'Jonson',
      'Joojo',
      'Jordan',
      'Jordi',
      'Jordon',
      'Jordy',
      'Jordyn',
      'Jorge',
      'Joris',
      'Jorryn',
      'Josan',
      'Josef',
      'Joseph',
      'Josese',
      'Josh',
      'Joshiah',
      'Joshua',
      'Josiah',
      'Joss',
      'Jostelle',
      'Joynul',
      'Juan',
      'Jubin',
      'Judah',
      'Jude',
      'Jules',
      'Julian',
      'Julien',
      'Jun',
      'Junior',
      'Jura',
      'Justan',
      'Justin',
      'Justinas',
      'Kaan',
      'Kabeer',
      'Kabir',
      'Kacey',
      'Kacper',
      'Kade',
      'Kaden',
      'Kadin',
      'Kadyn',
      'Kaeden',
      'Kael',
      'Kaelan',
      'Kaelin',
      'Kaelum',
      'Kai',
      'Kaid',
      'Kaidan',
      'Kaiden',
      'Kaidinn',
      'Kaidyn',
      'Kaileb',
      'Kailin',
      'Kain',
      'Kaine',
      'Kainin',
      'Kainui',
      'Kairn',
      'Kaison',
      'Kaiwen',
      'Kajally',
      'Kajetan',
      'Kalani',
      'Kale',
      'Kaleb',
      'Kaleem',
      'Kal-el',
      'Kalen',
      'Kalin',
      'Kallan',
      'Kallin',
      'Kalum',
      'Kalvin',
      'Kalvyn',
      'Kameron',
      'Kames',
      'Kamil',
      'Kamran',
      'Kamron',
      'Kane',
      'Karam',
      'Karamvir',
      'Karandeep',
      'Kareem',
      'Karim',
      'Karimas',
      'Karl',
      'Karol',
      'Karson',
      'Karsyn',
      'Karthikeya',
      'Kasey',
      'Kash',
      'Kashif',
      'Kasim',
      'Kasper',
      'Kasra',
      'Kavin',
      'Kayam',
      'Kaydan',
      'Kayden',
      'Kaydin',
      'Kaydn',
      'Kaydyn',
      'Kaydyne',
      'Kayleb',
      'Kaylem',
      'Kaylum',
      'Kayne',
      'Kaywan',
      'Kealan',
      'Kealon',
      'Kean',
      'Keane',
      'Kearney',
      'Keatin',
      'Keaton',
      'Keavan',
      'Keayn',
      'Kedrick',
      'Keegan',
      'Keelan',
      'Keelin',
      'Keeman',
      'Keenan',
      'Keenan-Lee',
      'Keeton',
      'Kehinde',
      'Keigan',
      'Keilan',
      'Keir',
      'Keiran',
      'Keiren',
      'Keiron',
      'Keiryn',
      'Keison',
      'Keith',
      'Keivlin',
      'Kelam',
      'Kelan',
      'Kellan',
      'Kellen',
      'Kelso',
      'Kelum',
      'Kelvan',
      'Kelvin',
      'Ken',
      'Kenan',
      'Kendall',
      'Kendyn',
      'Kenlin',
      'Kenneth',
      'Kensey',
      'Kenton',
      'Kenyon',
      'Kenzeigh',
      'Kenzi',
      'Kenzie',
      'Kenzo',
      'Kenzy',
      'Keo',
      'Ker',
      'Kern',
      'Kerr',
      'Kevan',
      'Kevin',
      'Kevyn',
      'Kez',
      'Khai',
      'Khalan',
      'Khaleel',
      'Khaya',
      'Khevien',
      'Khizar',
      'Khizer',
      'Kia',
      'Kian',
      'Kian-James',
      'Kiaran',
      'Kiarash',
      'Kie',
      'Kiefer',
      'Kiegan',
      'Kienan',
      'Kier',
      'Kieran',
      'Kieran-Scott',
      'Kieren',
      'Kierin',
      'Kiern',
      'Kieron',
      'Kieryn',
      'Kile',
      'Killian',
      'Kimi',
      'Kingston',
      'Kinneil',
      'Kinnon',
      'Kinsey',
      'Kiran',
      'Kirk',
      'Kirwin',
      'Kit',
      'Kiya',
      'Kiyonari',
      'Kjae',
      'Klein',
      'Klevis',
      'Kobe',
      'Kobi',
      'Koby',
      'Koddi',
      'Koden',
      'Kodi',
      'Kodie',
      'Kody',
      'Kofi',
      'Kogan',
      'Kohen',
      'Kole',
      'Konan',
      'Konar',
      'Konnor',
      'Konrad',
      'Koray',
      'Korben',
      'Korbyn',
      'Korey',
      'Kori',
      'Korrin',
      'Kory',
      'Koushik',
      'Kris',
      'Krish',
      'Krishan',
      'Kriss',
      'Kristian',
      'Kristin',
      'Kristofer',
      'Kristoffer',
      'Kristopher',
      'Kruz',
      'Krzysiek',
      'Krzysztof',
      'Ksawery',
      'Ksawier',
      'Kuba',
      'Kurt',
      'Kurtis',
      'Kurtis-Jae',
      'Kyaan',
      'Kyan',
      'Kyde',
      'Kyden',
      'Kye',
      'Kyel',
      'Kyhran',
      'Kyie',
      'Kylan',
      'Kylar',
      'Kyle',
      'Kyle-Derek',
      'Kylian',
      'Kym',
      'Kynan',
      'Kyral',
      'Kyran',
      'Kyren',
      'Kyrillos',
      'Kyro',
      'Kyron',
      'Kyrran',
      'Lachlainn',
      'Lachlan',
      'Lachlann',
      'Lael',
      'Lagan',
      'Laird',
      'Laison',
      'Lakshya',
      'Lance',
      'Lancelot',
      'Landon',
      'Lang',
      'Lasse',
      'Latif',
      'Lauchlan',
      'Lauchlin',
      'Laughlan',
      'Lauren',
      'Laurence',
      'Laurie',
      'Lawlyn',
      'Lawrence',
      'Lawrie',
      'Lawson',
      'Layne',
      'Layton',
      'Lee',
      'Leigh',
      'Leigham',
      'Leighton',
      'Leilan',
      'Leiten',
      'Leithen',
      'Leland',
      'Lenin',
      'Lennan',
      'Lennen',
      'Lennex',
      'Lennon',
      'Lennox',
      'Lenny',
      'Leno',
      'Lenon',
      'Lenyn',
      'Leo',
      'Leon',
      'Leonard',
      'Leonardas',
      'Leonardo',
      'Lepeng',
      'Leroy',
      'Leven',
      'Levi',
      'Levon',
      'Levy',
      'Lewie',
      'Lewin',
      'Lewis',
      'Lex',
      'Leydon',
      'Leyland',
      'Leylann',
      'Leyton',
      'Liall',
      'Liam',
      'Liam-Stephen',
      'Limo',
      'Lincoln',
      'Lincoln-John',
      'Lincon',
      'Linden',
      'Linton',
      'Lionel',
      'Lisandro',
      'Litrell',
      'Liyonela-Elam',
      'LLeyton',
      'Lliam',
      'Lloyd',
      'Lloyde',
      'Loche',
      'Lochlan',
      'Lochlann',
      'Lochlan-Oliver',
      'Lock',
      'Lockey',
      'Logan',
      'Logann',
      'Logan-Rhys',
      'Loghan',
      'Lokesh',
      'Loki',
      'Lomond',
      'Lorcan',
      'Lorenz',
      'Lorenzo',
      'Lorne',
      'Loudon',
      'Loui',
      'Louie',
      'Louis',
      'Loukas',
      'Lovell',
      'Luc',
      'Luca',
      'Lucais',
      'Lucas',
      'Lucca',
      'Lucian',
      'Luciano',
      'Lucien',
      'Lucus',
      'Luic',
      'Luis',
      'Luk',
      'Luka',
      'Lukas',
      'Lukasz',
      'Luke',
      'Lukmaan',
      'Luqman',
      'Lyall',
      'Lyle',
      'Lyndsay',
      'Lysander',
      'Maanav',
      'Maaz',
      'Mac',
      'Macallum',
      'Macaulay',
      'Macauley',
      'Macaully',
      'Machlan',
      'Maciej',
      'Mack',
      'Mackenzie',
      'Mackenzy',
      'Mackie',
      'Macsen',
      'Macy',
      'Madaki',
      'Maddison',
      'Maddox',
      'Madison',
      'Madison-Jake',
      'Madox',
      'Mael',
      'Magnus',
      'Mahan',
      'Mahdi',
      'Mahmoud',
      'Maias',
      'Maison',
      'Maisum',
      'Maitlind',
      'Majid',
      'Makensie',
      'Makenzie',
      'Makin',
      'Maksim',
      'Maksymilian',
      'Malachai',
      'Malachi',
      'Malachy',
      'Malakai',
      'Malakhy',
      'Malcolm',
      'Malik',
      'Malikye',
      'Malo',
      "Ma'moon",
      'Manas',
      'Maneet',
      'Manmohan',
      'Manolo',
      'Manson',
      'Mantej',
      'Manuel',
      'Manus',
      'Marc',
      'Marc-Anthony',
      'Marcel',
      'Marcello',
      'Marcin',
      'Marco',
      'Marcos',
      'Marcous',
      'Marcquis',
      'Marcus',
      'Mario',
      'Marios',
      'Marius',
      'Mark',
      'Marko',
      'Markus',
      'Marley',
      'Marlin',
      'Marlon',
      'Maros',
      'Marshall',
      'Martin',
      'Marty',
      'Martyn',
      'Marvellous',
      'Marvin',
      'Marwan',
      'Maryk',
      'Marzuq',
      'Mashhood',
      'Mason',
      'Mason-Jay',
      'Masood',
      'Masson',
      'Matas',
      'Matej',
      'Mateusz',
      'Mathew',
      'Mathias',
      'Mathu',
      'Mathuyan',
      'Mati',
      'Matt',
      'Matteo',
      'Matthew',
      'Matthew-William',
      'Matthias',
      'Max',
      'Maxim',
      'Maximilian',
      'Maximillian',
      'Maximus',
      'Maxwell',
      'Maxx',
      'Mayeul',
      'Mayson',
      'Mazin',
      'Mcbride',
      'McCaulley',
      'McKade',
      'McKauley',
      'McKay',
      'McKenzie',
      'McLay',
      'Meftah',
      'Mehmet',
      'Mehraz',
      'Meko',
      'Melville',
      'Meshach',
      'Meyzhward',
      'Micah',
      'Michael',
      'Michael-Alexander',
      'Michael-James',
      'Michal',
      'Michat',
      'Micheal',
      'Michee',
      'Mickey',
      'Miguel',
      'Mika',
      'Mikael',
      'Mikee',
      'Mikey',
      'Mikhail',
      'Mikolaj',
      'Miles',
      'Millar',
      'Miller',
      'Milo',
      'Milos',
      'Milosz',
      'Mir',
      'Mirza',
      'Mitch',
      'Mitchel',
      'Mitchell',
      'Moad',
      'Moayd',
      'Mobeen',
      'Modoulamin',
      'Modu',
      'Mohamad',
      'Mohamed',
      'Mohammad',
      'Mohammad-Bilal',
      'Mohammed',
      'Mohanad',
      'Mohd',
      'Momin',
      'Momooreoluwa',
      'Montague',
      'Montgomery',
      'Monty',
      'Moore',
      'Moosa',
      'Moray',
      'Morgan',
      'Morgyn',
      'Morris',
      'Morton',
      'Moshy',
      'Motade',
      'Moyes',
      'Msughter',
      'Mueez',
      'Muhamadjavad',
      'Muhammad',
      'Muhammed',
      'Muhsin',
      'Muir',
      'Munachi',
      'Muneeb',
      'Mungo',
      'Munir',
      'Munmair',
      'Munro',
      'Murdo',
      'Murray',
      'Murrough',
      'Murry',
      'Musa',
      'Musse',
      'Mustafa',
      'Mustapha',
      'Muzammil',
      'Muzzammil',
      'Mykie',
      'Myles',
      'Mylo',
      'Nabeel',
      'Nadeem',
      'Nader',
      'Nagib',
      'Naif',
      'Nairn',
      'Narvic',
      'Nash',
      'Nasser',
      'Nassir',
      'Natan',
      'Nate',
      'Nathan',
      'Nathanael',
      'Nathanial',
      'Nathaniel',
      'Nathan-Rae',
      'Nawfal',
      'Nayan',
      'Neco',
      'Neil',
      'Nelson',
      'Neo',
      'Neshawn',
      'Nevan',
      'Nevin',
      'Ngonidzashe',
      'Nial',
      'Niall',
      'Nicholas',
      'Nick',
      'Nickhill',
      'Nicki',
      'Nickson',
      'Nicky',
      'Nico',
      'Nicodemus',
      'Nicol',
      'Nicolae',
      'Nicolas',
      'Nidhish',
      'Nihaal',
      'Nihal',
      'Nikash',
      'Nikhil',
      'Niki',
      'Nikita',
      'Nikodem',
      'Nikolai',
      'Nikos',
      'Nilav',
      'Niraj',
      'Niro',
      'Niven',
      'Noah',
      'Noel',
      'Nolan',
      'Noor',
      'Norman',
      'Norrie',
      'Nuada',
      'Nyah',
      'Oakley',
      'Oban',
      'Obieluem',
      'Obosa',
      'Odhran',
      'Odin',
      'Odynn',
      'Ogheneochuko',
      'Ogheneruno',
      'Ohran',
      'Oilibhear',
      'Oisin',
      'Ojima-Ojo',
      'Okeoghene',
      'Olaf',
      'Ola-Oluwa',
      'Olaoluwapolorimi',
      'Ole',
      'Olie',
      'Oliver',
      'Olivier',
      'Oliwier',
      'Ollie',
      'Olurotimi',
      'Oluwadamilare',
      'Oluwadamiloju',
      'Oluwafemi',
      'Oluwafikunayomi',
      'Oluwalayomi',
      'Oluwatobiloba',
      'Oluwatoni',
      'Omar',
      'Omri',
      'Oran',
      'Orin',
      'Orlando',
      'Orley',
      'Orran',
      'Orrick',
      'Orrin',
      'Orson',
      'Oryn',
      'Oscar',
      'Osesenagha',
      'Oskar',
      'Ossian',
      'Oswald',
      'Otto',
      'Owain',
      'Owais',
      'Owen',
      'Owyn',
      'Oz',
      'Ozzy',
      'Pablo',
      'Pacey',
      'Padraig',
      'Paolo',
      'Pardeepraj',
      'Parkash',
      'Parker',
      'Pascoe',
      'Pasquale',
      'Patrick',
      'Patrick-John',
      'Patrikas',
      'Patryk',
      'Paul',
      'Pavit',
      'Pawel',
      'Pawlo',
      'Pearce',
      'Pearse',
      'Pearsen',
      'Pedram',
      'Pedro',
      'Peirce',
      'Peiyan',
      'Pele',
      'Peni',
      'Peregrine',
      'Peter',
      'Phani',
      'Philip',
      'Philippos',
      'Phinehas',
      'Phoenix',
      'Phoevos',
      'Pierce',
      'Pierre-Antoine',
      'Pieter',
      'Pietro',
      'Piotr',
      'Porter',
      'Prabhjoit',
      'Prabodhan',
      'Praise',
      'Pranav',
      'Pravin',
      'Precious',
      'Prentice',
      'Presley',
      'Preston',
      'Preston-Jay',
      'Prinay',
      'Prince',
      'Prithvi',
      'Promise',
      'Puneetpaul',
      'Pushkar',
      'Qasim',
      'Qirui',
      'Quinlan',
      'Quinn',
      'Radmiras',
      'Raees',
      'Raegan',
      'Rafael',
      'Rafal',
      'Rafferty',
      'Rafi',
      'Raheem',
      'Rahil',
      'Rahim',
      'Rahman',
      'Raith',
      'Raithin',
      'Raja',
      'Rajab-Ali',
      'Rajan',
      'Ralfs',
      'Ralph',
      'Ramanas',
      'Ramit',
      'Ramone',
      'Ramsay',
      'Ramsey',
      'Rana',
      'Ranolph',
      'Raphael',
      'Rasmus',
      'Rasul',
      'Raul',
      'Raunaq',
      'Ravin',
      'Ray',
      'Rayaan',
      'Rayan',
      'Rayane',
      'Rayden',
      'Rayhan',
      'Raymond',
      'Rayne',
      'Rayyan',
      'Raza',
      'Reace',
      'Reagan',
      'Reean',
      'Reece',
      'Reed',
      'Reegan',
      'Rees',
      'Reese',
      'Reeve',
      'Regan',
      'Regean',
      'Reggie',
      'Rehaan',
      'Rehan',
      'Reice',
      'Reid',
      'Reigan',
      'Reilly',
      'Reily',
      'Reis',
      'Reiss',
      'Remigiusz',
      'Remo',
      'Remy',
      'Ren',
      'Renars',
      'Reng',
      'Rennie',
      'Reno',
      'Reo',
      'Reuben',
      'Rexford',
      'Reynold',
      'Rhein',
      'Rheo',
      'Rhett',
      'Rheyden',
      'Rhian',
      'Rhoan',
      'Rholmark',
      'Rhoridh',
      'Rhuairidh',
      'Rhuan',
      'Rhuaridh',
      'Rhudi',
      'Rhy',
      'Rhyan',
      'Rhyley',
      'Rhyon',
      'Rhys',
      'Rhys-Bernard',
      'Rhyse',
      'Riach',
      'Rian',
      'Ricards',
      'Riccardo',
      'Ricco',
      'Rice',
      'Richard',
      'Richey',
      'Richie',
      'Ricky',
      'Rico',
      'Ridley',
      'Ridwan',
      'Rihab',
      'Rihan',
      'Rihards',
      'Rihonn',
      'Rikki',
      'Riley',
      'Rio',
      'Rioden',
      'Rishi',
      'Ritchie',
      'Rivan',
      'Riyadh',
      'Riyaj',
      'Roan',
      'Roark',
      'Roary',
      'Rob',
      'Robbi',
      'Robbie',
      'Robbie-lee',
      'Robby',
      'Robert',
      'Robert-Gordon',
      'Robertjohn',
      'Robi',
      'Robin',
      'Rocco',
      'Roddy',
      'Roderick',
      'Rodrigo',
      'Roen',
      'Rogan',
      'Roger',
      'Rohaan',
      'Rohan',
      'Rohin',
      'Rohit',
      'Rokas',
      'Roman',
      'Ronald',
      'Ronan',
      'Ronan-Benedict',
      'Ronin',
      'Ronnie',
      'Rooke',
      'Roray',
      'Rori',
      'Rorie',
      'Rory',
      'Roshan',
      'Ross',
      'Ross-Andrew',
      'Rossi',
      'Rowan',
      'Rowen',
      'Roy',
      'Ruadhan',
      'Ruaidhri',
      'Ruairi',
      'Ruairidh',
      'Ruan',
      'Ruaraidh',
      'Ruari',
      'Ruaridh',
      'Ruben',
      'Rubhan',
      'Rubin',
      'Rubyn',
      'Rudi',
      'Rudy',
      'Rufus',
      'Rui',
      'Ruo',
      'Rupert',
      'Ruslan',
      'Russel',
      'Russell',
      'Ryaan',
      'Ryan',
      'Ryan-Lee',
      'Ryden',
      'Ryder',
      'Ryese',
      'Ryhs',
      'Rylan',
      'Rylay',
      'Rylee',
      'Ryleigh',
      'Ryley',
      'Rylie',
      'Ryo',
      'Ryszard',
      'Saad',
      'Sabeen',
      'Sachkirat',
      'Saffi',
      'Saghun',
      'Sahaib',
      'Sahbian',
      'Sahil',
      'Saif',
      'Saifaddine',
      'Saim',
      'Sajid',
      'Sajjad',
      'Salahudin',
      'Salman',
      'Salter',
      'Salvador',
      'Sam',
      'Saman',
      'Samar',
      'Samarjit',
      'Samatar',
      'Sambrid',
      'Sameer',
      'Sami',
      'Samir',
      'Sami-Ullah',
      'Samual',
      'Samuel',
      'Samuela',
      'Samy',
      'Sanaullah',
      'Sandro',
      'Sandy',
      'Sanfur',
      'Sanjay',
      'Santiago',
      'Santino',
      'Satveer',
      'Saul',
      'Saunders',
      'Savin',
      'Sayad',
      'Sayeed',
      'Sayf',
      'Scot',
      'Scott',
      'Scott-Alexander',
      'Seaan',
      'Seamas',
      'Seamus',
      'Sean',
      'Seane',
      'Sean-James',
      'Sean-Paul',
      'Sean-Ray',
      'Seb',
      'Sebastian',
      'Sebastien',
      'Selasi',
      'Seonaidh',
      'Sephiroth',
      'Sergei',
      'Sergio',
      'Seth',
      'Sethu',
      'Seumas',
      'Shaarvin',
      'Shadow',
      'Shae',
      'Shahmir',
      'Shai',
      'Shane',
      'Shannon',
      'Sharland',
      'Sharoz',
      'Shaughn',
      'Shaun',
      'Shaunpaul',
      'Shaun-Paul',
      'Shaun-Thomas',
      'Shaurya',
      'Shaw',
      'Shawn',
      'Shawnpaul',
      'Shay',
      'Shayaan',
      'Shayan',
      'Shaye',
      'Shayne',
      'Shazil',
      'Shea',
      'Sheafan',
      'Sheigh',
      'Shenuk',
      'Sher',
      'Shergo',
      'Sheriff',
      'Sherwyn',
      'Shiloh',
      'Shiraz',
      'Shreeram',
      'Shreyas',
      'Shyam',
      'Siddhant',
      'Siddharth',
      'Sidharth',
      'Sidney',
      'Siergiej',
      'Silas',
      'Simon',
      'Sinai',
      'Skye',
      'Sofian',
      'Sohaib',
      'Sohail',
      'Soham',
      'Sohan',
      'Sol',
      'Solomon',
      'Sonneey',
      'Sonni',
      'Sonny',
      'Sorley',
      'Soul',
      'Spencer',
      'Spondon',
      'Stanislaw',
      'Stanley',
      'Stefan',
      'Stefano',
      'Stefin',
      'Stephen',
      'Stephenjunior',
      'Steve',
      'Steven',
      'Steven-lee',
      'Stevie',
      'Stewart',
      'Stewarty',
      'Strachan',
      'Struan',
      'Stuart',
      'Su',
      'Subhaan',
      'Sudais',
      'Suheyb',
      'Suilven',
      'Sukhi',
      'Sukhpal',
      'Sukhvir',
      'Sulayman',
      'Sullivan',
      'Sultan',
      'Sung',
      'Sunny',
      'Suraj',
      'Surien',
      'Sweyn',
      'Syed',
      'Sylvain',
      'Symon',
      'Szymon',
      'Tadd',
      'Taddy',
      'Tadhg',
      'Taegan',
      'Taegen',
      'Tai',
      'Tait',
      'Taiwo',
      'Talha',
      'Taliesin',
      'Talon',
      'Talorcan',
      'Tamar',
      'Tamiem',
      'Tammam',
      'Tanay',
      'Tane',
      'Tanner',
      'Tanvir',
      'Tanzeel',
      'Taonga',
      'Tarik',
      'Tariq-Jay',
      'Tate',
      'Taylan',
      'Taylar',
      'Tayler',
      'Taylor',
      'Taylor-Jay',
      'Taylor-Lee',
      'Tayo',
      'Tayyab',
      'Tayye',
      'Tayyib',
      'Teagan',
      'Tee',
      'Teejay',
      'Tee-jay',
      'Tegan',
      'Teighen',
      'Teiyib',
      'Te-Jay',
      'Temba',
      'Teo',
      'Teodor',
      'Teos',
      'Terry',
      'Teydren',
      'Theo',
      'Theodore',
      'Thiago',
      'Thierry',
      'Thom',
      'Thomas',
      'Thomas-Jay',
      'Thomson',
      'Thorben',
      'Thorfinn',
      'Thrinei',
      'Thumbiko',
      'Tiago',
      'Tian',
      'Tiarnan',
      'Tibet',
      'Tieran',
      'Tiernan',
      'Timothy',
      'Timucin',
      'Tiree',
      'Tisloh',
      'Titi',
      'Titus',
      'Tiylar',
      'TJ',
      'Tjay',
      'T-Jay',
      'Tobey',
      'Tobi',
      'Tobias',
      'Tobie',
      'Toby',
      'Todd',
      'Tokinaga',
      'Toluwalase',
      'Tom',
      'Tomas',
      'Tomasz',
      'Tommi-Lee',
      'Tommy',
      'Tomson',
      'Tony',
      'Torin',
      'Torquil',
      'Torran',
      'Torrin',
      'Torsten',
      'Trafford',
      'Trai',
      'Travis',
      'Tre',
      'Trent',
      'Trey',
      'Tristain',
      'Tristan',
      'Troy',
      'Tubagus',
      'Turki',
      'Turner',
      'Ty',
      'Ty-Alexander',
      'Tye',
      'Tyelor',
      'Tylar',
      'Tyler',
      'Tyler-James',
      'Tyler-Jay',
      'Tyllor',
      'Tylor',
      'Tymom',
      'Tymon',
      'Tymoteusz',
      'Tyra',
      'Tyree',
      'Tyrnan',
      'Tyrone',
      'Tyson',
      'Ubaid',
      'Ubayd',
      'Uchenna',
      'Uilleam',
      'Umair',
      'Umar',
      'Umer',
      'Umut',
      'Urban',
      'Uri',
      'Usman',
      'Uzair',
      'Uzayr',
      'Valen',
      'Valentin',
      'Valentino',
      'Valery',
      'Valo',
      'Vasyl',
      'Vedantsinh',
      'Veeran',
      'Victor',
      'Victory',
      'Vinay',
      'Vince',
      'Vincent',
      'Vincenzo',
      'Vinh',
      'Vinnie',
      'Vithujan',
      'Vladimir',
      'Vladislav',
      'Vrishin',
      'Vuyolwethu',
      'Wabuya',
      'Wai',
      'Walid',
      'Wallace',
      'Walter',
      'Waqaas',
      'Warkhas',
      'Warren',
      'Warrick',
      'Wasif',
      'Wayde',
      'Wayne',
      'Wei',
      'Wen',
      'Wesley',
      'Wesley-Scott',
      'Wiktor',
      'Wilkie',
      'Will',
      'William',
      'William-John',
      'Willum',
      'Wilson',
      'Windsor',
      'Wojciech',
      'Woyenbrakemi',
      'Wyatt',
      'Wylie',
      'Wynn',
      'Xabier',
      'Xander',
      'Xavier',
      'Xiao',
      'Xida',
      'Xin',
      'Xue',
      'Yadgor',
      'Yago',
      'Yahya',
      'Yakup',
      'Yang',
      'Yanick',
      'Yann',
      'Yannick',
      'Yaseen',
      'Yasin',
      'Yasir',
      'Yassin',
      'Yoji',
      'Yong',
      'Yoolgeun',
      'Yorgos',
      'Youcef',
      'Yousif',
      'Youssef',
      'Yu',
      'Yuanyu',
      'Yuri',
      'Yusef',
      'Yusuf',
      'Yves',
      'Zaaine',
      'Zaak',
      'Zac',
      'Zach',
      'Zachariah',
      'Zacharias',
      'Zacharie',
      'Zacharius',
      'Zachariya',
      'Zachary',
      'Zachary-Marc',
      'Zachery',
      'Zack',
      'Zackary',
      'Zaid',
      'Zain',
      'Zaine',
      'Zaineddine',
      'Zainedin',
      'Zak',
      'Zakaria',
      'Zakariya',
      'Zakary',
      'Zaki',
      'Zakir',
      'Zakk',
      'Zamaar',
      'Zander',
      'Zane',
      'Zarran',
      'Zayd',
      'Zayn',
      'Zayne',
      'Ze',
      'Zechariah',
      'Zeek',
      'Zeeshan',
      'Zeid',
      'Zein',
      'Zen',
      'Zendel',
      'Zenith',
      'Zennon',
      'Zeph',
      'Zerah',
      'Zhen',
      'Zhi',
      'Zhong',
      'Zhuo',
      'Zi',
      'Zidane',
      'Zijie',
      'Zinedine',
      'Zion',
      'Zishan',
      'Ziya',
      'Ziyaan',
      'Zohaib',
      'Zohair',
      'Zoubaeir',
      'Zubair',
      'Zubayr',
      'Zuriel',
   ];

   const usedNames: string[] = [];

   const categories: string[] = [
      't-shirt',
      'shirts',
      'dresses',
      'skirts',
      'shorts',
      'pants',
      'socks',
   ];

   const response: string = await fetch(
      'https://br.depositphotos.com/stock-photos/pedra.html'
   ).then(res => res.text());

   let pictureTagFilter: RegExp = new RegExp(
      '(<picture>)(.+?)(</picture>)',
      'gi'
   );

   let picturesTag: RegExpMatchArray | null = response.match(pictureTagFilter);

   let imgSrcFilter: RegExp = new RegExp('(?<=src=")(.+?)(?=")', 'gi');

   if (typeof picturesTag != null) {
      let imgSrcs: Product[] = (picturesTag as RegExpMatchArray)
         .map(e => {
            let filteredElement: RegExpMatchArray | null =
               e.match(imgSrcFilter);

            if (typeof filteredElement != null) {
               return (filteredElement as RegExpMatchArray)[0];
            }
         })
         .map((e, i) => {
            let random: number = Math.floor(Math.random() * names.length);
            let name: string = names[random];

            let randomCategory: number = Math.floor(
               Math.random() * categories.length
            );

            let category: string = categories[randomCategory];

            while (usedNames.includes(name)) {
               random = Math.floor(Math.random() * names.length);
               name = names[random];
            }

            usedNames.push(name);

            const obj: Product = {
               image: e as string,
               category,
               name: `Pedra ${name}`,
               description: generateDescription(`Pedra ${name}`),
               id: i + 1,
               sales: Math.floor(Math.random() * 2000),
            };

            return obj;
         });

      res.status(200).json({ imgSrcs });
   }
}

function generateDescription(stoneName: string): string {
   var names1 = [
      'Black',
      'Gray',
      'White',
      'Blonde',
      'Brown',
      'Red',
      'Ginger',
      'Chestnut',
      'Silver',
   ];
   var names2 = [
      'short hair',
      'short spiky hair',
      'short bristly hair',
      'well groomed hair',
      'crinkly hair',
      'sleek hair',
      'flowing hair',
      'shaggy hair',
      'well groomed hair',
      'long hair',
      'curly hair',
      'straight hair',
      'wavy hair',
      'frizzy hair',
      'coily hair',
      'long hair',
      'curly hair',
      'straight hair',
      'wavy hair',
      'frizzy hair',
      'coily hair',
      'dreadlocks',
      'shoulder-length hair',
   ];
   var names3 = [
      'hangs over',
      'slightly reveals',
      'tight in a ponytail reveals',
      'gently hangs over',
      'slightly covers',
      'almost fully covers',
      'clumsily hangs over',
      'awkwardly hangs over',
      'neatly coiffured to reveal',
      'is pulled back to reveal',
   ];
   var names4 = [
      'thin',
      'chiseled',
      'craggy',
      'fine',
      'fresh',
      'full',
      'furrowed',
      'handsome',
      'sculpted',
      'weak',
      'strong',
      'long',
      'round',
      'bony',
      'lean',
      'skinny',
      'fat',
   ];
   var names5 = [
      'time-worn',
      'cheerful',
      'friendly',
      'charming',
      'radiant',
      'warm',
      'anguished',
      'menacing',
      'lively',
      'tense',
      'wild',
      'gloomy',
      'frowning',
      'worried',
      'sad',
      'lived-in',
   ];
   var names6 = [
      'Beady',
      'Big, round',
      'Bloodshot',
      'Bright',
      'Bulging',
      'Clear',
      'Dancing',
      'Darting',
      'Dead',
      'Expressive',
      'Gentle',
      'Glinting',
      'Glistening',
      'Glittering',
      'Heavy',
      'Hollow',
      'Hooded',
      'Lidded',
      'Narrow',
      'Piercing',
      'Round',
      'Shining',
      'Shuttered',
      'Small',
      'Smart',
      'Sparkling',
      'Squinting',
      'Wide',
      'Woeful',
   ];
   var names7 = ['blue', 'brown', 'hazel', 'black', 'green', 'amber', 'gray'];
   var names8 = [
      'deep',
      'narrowly',
      'buried',
      'far',
      'rooted',
      'well',
      'low',
      'high',
      'sunken',
      'lightly',
      'thightly',
      'graciously',
      'concealed',
      'delicately',
      'elegantly',
      'handsomely',
      'a-symmetrically',
      'gracefully',
      'seductively',
      'appealingly',
      'charmingly',
      'dreadfully',
      'wickedly',
   ];
   var names9 = [
      'wearily',
      'delightfully',
      'cheerfully',
      'gratefully',
      'heartily',
      'warmly',
      'eagerly',
      'delightedly',
      'merrily',
      'lovingly',
      'enthusiastically',
      'readily',
      'hungrily',
      'intently',
      'energetically',
      'impatiently',
      'longingly',
      'vigorously',
      'rapidly',
      'admiringly',
      'affectionately',
      'fondly',
      'thoughtfully',
      'devotedly',
      'yearningly',
      'loyally',
      'cautiously',
      'slowly',
      'carefully',
      'guardedly',
      'discreetly',
      'anxiously',
      'attentively',
      'meticulously',
      'honorably',
      'vigilantly',
      'watchfully',
      'delicately',
      'faithfully',
   ];
   var names10 = [
      'village',
      'city',
      'lands',
      'people',
      'town',
      'families',
      'ships',
      'armies',
      'homes',
      'castle',
      'palace',
      'natives',
      'wildlife',
      'farms',
      'country',
      'haven',
      'mountains',
      'rivers',
      'river',
      'sea',
      'woods',
      'wastelands',
      'clan',
      'folk',
      'tribe',
      'ancestors',
      'children',
      'deserts',
      'mines',
      'spirits',
      'stronghold',
   ];
   var names11 = [
      'protected',
      'sworn to protect',
      'come to love',
      'loved',
      'fought for',
      'bled for',
      'nearly died for',
      'looked after',
      'cared for',
      'defended',
      'safeguarded',
      'kept safe',
      'watched over',
      'stood guard for',
      'come to appreciate',
      'grown affactionate of',
      'become enchancted by',
      'worshipped',
      'befriended',
      'grieved with',
      'shown mercy on',
      'sought solace in',
      'felt at home at',
      'rarely felt at home at',
      'barely related to',
      'disassociated with',
      'felt disconnected from',
      'have been seperated from',
      'been seperated from',
      'been isolated from',
   ];
   var names12 = [
      'A scar',
      'Scars',
      'A sword left a mark',
      'A gunshot left a mark',
      'Fallen debry left a mark',
      'Fire has left a mark',
      'A birthmark',
      'An old tattoo',
      'A tattoo',
      'Tribal marks',
      'Several moles',
      'Freckles',
      'Smooth skin',
      'Soft skin',
      'Fair skin',
      'A beard',
      'A large beard',
      'Dark stubble',
      'A moustache',
      'A goatee',
      'A moustache and goatee',
   ];
   var names13 = [
      'stretching from just under the right eye',
      'stretching from just under the left eye',
      'stretching from just under the right eyebrow',
      'stretching from just under the left eyebrow',
      'stretching from just under the right eye',
      'stretching from the top of the right cheek',
      'stretching from the top of the left cheek',
      'stretching from the bottom of the right cheek',
      'stretching from the bottom of the left cheek',
      'stretching from the bottom of the right cheekbone',
      'stretching from the bottom of the left cheekbone',
      'stretching from the right side of the forehead',
      'stretching from the left side of the forehead',
      'reaching from just under the right eye',
      'reaching from just under the left eye',
      'reaching from just under the right eyebrow',
      'reaching from just under the left eyebrow',
      'reaching from just under the right eye',
      'reaching from the top of the right cheek',
      'reaching from the top of the left cheek',
      'reaching from the bottom of the right cheek',
      'reaching from the bottom of the left cheek',
      'reaching from the bottom of the right cheekbone',
      'reaching from the bottom of the left cheekbone',
      'reaching from the right side of the forehead',
      'reaching from the left side of the forehead',
   ];
   var names14 = [
      ', running across the nose',
      ', running towards the other eye',
      ', first running towards thin lips',
      ', first running towards his fairly big lips',
      ', running towards the right side of his lips',
      ', running towards the left side of his lips',
      ', running towards the tip of the nose',
      ', running towards his left nostril',
      ', running towards his right nostril',
      ', running towards his upper lip',
   ];
   var names15 = [
      'and ending on his left cheek',
      'and ending on his left cheekbone',
      'and ending on his right cheek',
      'and ending on his right cheekbone',
      'and ending on his upper lip',
      'and ending on his chin',
      'and ending on his forehead',
      'and ending on his right nostril',
      'and ending on his left nostril',
      'and ending under his left eye',
      'and ending under his right eye',
      'and ending above his right eye',
      'and ending above his left eye',
   ];
   var names16 = [
      'a pleasant memory',
      'an aching memory',
      'a burning memory',
      'a stinging memory',
      'a tormenting memory',
      'an aching burden',
      'a stinging burden',
      'a tormenting burden',
      'a painful burden',
      'a lasting punishment',
      'a lasting burden',
      'an amusing memory',
      'a delightful memory',
      'a gracious memory',
      'a pleasurable memory',
      'a bittersweet memory',
      'a heartbreaking memory',
      'an agonizing memory',
      'a grievous memory',
      'a beautiful memory',
      'a satisfying memory',
      'a fascinating memory',
      'a captivating memory',
      'an intriguing memory',
      'a compelling memory',
   ];
   var names17 = [
      'a former life',
      'a great reputation',
      'a new life',
      'a reclaimed home',
      'an unusual alliance',
      'battles long forgotten',
      'battles past',
      'companionship',
      'deceased love',
      'deceased loved ones',
      'defended homes',
      'defended honor',
      'defended lands',
      'departed love',
      'departed loved ones',
      'famed glory',
      'forbidden adventures',
      'forbidden love',
      'former lives',
      'former love',
      'fortunate adventures',
      'heroic liberations',
      'hidden talents',
      'his adventurous love life',
      'his ex-love',
      'his former lover',
      'his fortunate destiny',
      'his fortunate past',
      'his fortunate survival',
      'his fortunate upbringing',
      'his love',
      'his luck in battles',
      'his luck in love',
      'his luck',
      'his reckless luck',
      'his unfortunate past',
      'his unfortunate upbringing',
      'innocence long lost',
      'lands long forgotten',
      'liberated love',
      'lost comrades',
      'lost friends',
      'lost honor',
      'lost love',
      'reclaimed honor',
      'reclaimed lands',
      'redeemed honor',
      'redeemed love',
      'redemption',
      'restored honor',
      'return to home',
      'true friendship',
      'unexpected friendship',
      'unfortunate adventures',
   ];
   var names18 = [
      'Adam',
      'Adan',
      'Addison',
      'Brock',
      'Brodie',
      'Brody',
      'Brooks',
      'Bruce',
      'Bruno',
      'Bryan',
      'Bryant',
      'Bryce',
      'Brycen',
      'Bryson',
      'Byron',
      'Cade',
      'Caden',
      'Cael',
      'Caiden',
      'Cale',
      'Gunnar',
      'Irving',
      'Isaac',
      'Jamal',
      'Jamar',
      'Kade',
      'Maverick',
      'Max',
      'Orion',
      'Orlando',
   ];
   var names19 = [
      'Adwell',
      'Afton',
      'Barnett',
      'Barney',
      'Barnfield',
      'Chilson',
      'Chilton',
      'Cawthorn',
      'Davenport',
      'Davey',
      'Dallin',
      'Eustice',
      'Eustis',
      'Evatt',
      'Falcon',
      'Faley',
      'Falkner',
      'Geary',
      'Gedman',
      'Gedney',
      'Hanshaw',
      'Hansley',
      'Hanson',
      'Lamkin',
      'Lamkins',
      'Lamm',
      'Lockridge',
      'Locks',
      'Lockwood',
      'Masser',
      'Massey',
      'Massingale',
      'Rosemond',
      'Shepherd',
      'Shepley',
      'Wakeley',
      'Wakelin',
   ];
   var names20 = [
      'hero',
      'friend',
      'leader',
      'pioneer',
      'romancer',
      'fortune-hunter',
      'explorer',
      'daredevil',
      'globetrotter',
      'mercenary',
      'dreamer',
      'visionary',
      'idealist',
      'genius',
      'champion',
      'master',
      'prodigy',
      'spectacle',
      'guardian',
      'angel',
      'paladin',
      'warrior',
      'hunter',
      'warden',
      'defender',
      'sentinel',
      'victor',
      'winner',
      'challenger',
      'ally',
      'protector',
      'vanquisher',
      'vindicator',
      'romanticist',
      'stargazer',
      'nobleman',
      'utopian',
      'adventurer',
      'opportunist',
      'pioneer',
   ];
   var names21 = [
      'humans',
      'humans',
      'humans',
      'humans',
      'elves',
      'night elves',
      'blood elves',
      'high elves',
      'wood elves',
      'dark elves',
      'gnomes',
      'trolls',
      'orcs',
      'goblins',
      'dwarves',
      'giants',
      'halflings',
      'vampires',
      'werewolves',
   ];
   var names22 = [
      'tall among',
      'short among',
      'towering among',
      'towering above',
      'tall above',
      'big among',
      'high among',
      'small among',
      'average among',
      'ordinary among',
      'common among',
      'oddly among',
      'awkwardly among',
      'gracefully among',
      'graciously among',
      'elegantly among',
      'easily among',
      'tiny among',
      'seductively among',
      'alluringly among',
   ];
   var names23 = [
      'thin',
      'big',
      'fragile',
      'delicate',
      'lean',
      'narrow',
      'skinny',
      'slim',
      'light',
      'subtle',
      'scraggy',
      'bulky',
      'heavy',
      'hefty',
      'athletic',
      'brawny',
      'sturdy',
      'strong',
      'muscled',
      'tough',
   ];
   var names24 = [
      'alluring',
      'ambiguous',
      'appealing',
      'bewildering',
      'bizarre',
      'captivating',
      'charming',
      'curious',
      'different',
      'enigmatic',
      'enthralling',
      'enticing',
      'extraordinary',
      'fascinating',
      'incomprehensible',
      'inexplicable',
      'intriguing',
      'irregular',
      'misleading',
      'mystifying',
      'obscure',
      'odd',
      'puzzling',
      'seductive',
      'wonderful',
   ];
   var names25 = [
      'a feeling of anguish',
      'a feeling of arogance',
      'a feeling of coldness',
      'a feeling of comfort',
      'a feeling of delight',
      'a feeling of guilt',
      'a feeling of hospitality',
      'a feeling of indifference',
      'a feeling of joy',
      'a feeling of regret',
      'a feeling of remorse',
      'a feeling of sadness',
      'a feeling of shame',
      'his attitude',
      'his bravery',
      'his clumsiness',
      'his company',
      'his composure',
      'his decency',
      'his disposition',
      'his fortunate past',
      'his friendly demeanor',
      'his gentleness',
      'his good looks',
      'his good will',
      'his goodwill',
      'his hatred',
      'his humility',
      'his kindness',
      'his odd companions',
      'his odd friends',
      'his painful past',
      'his patience',
      'his perseverance',
      'his persistence',
      'his personality',
      'his presence',
      'his reputation',
      'his sense of comradery',
      'his sense of honor',
      'his sense of humor',
      'his sense of justice',
      'his sensitivity',
      'his suffering',
      'his sympathy',
      'his tenderness',
      'his unfortunate past',
      'his unusual alliances',
      'his unusual looks',
      'his warmth',
   ];
   var names26 = [
      'a feeling of anguish',
      'a feeling of arogance',
      'a feeling of coldness',
      'a feeling of comfort',
      'a feeling of delight',
      'a feeling of guilt',
      'a feeling of hospitality',
      'a feeling of indifference',
      'a feeling of joy',
      'a feeling of regret',
      'a feeling of remorse',
      'a feeling of sadness',
      'a feeling of shame',
      'his attitude',
      'his bravery',
      'his clumsiness',
      'his company',
      'his composure',
      'his decency',
      'his disposition',
      'his fortunate past',
      'his friendly demeanor',
      'his gentleness',
      'his good looks',
      'his good will',
      'his goodwill',
      'his hatred',
      'his humility',
      'his kindness',
      'his odd companions',
      'his odd friends',
      'his painful past',
      'his patience',
      'his perseverance',
      'his persistence',
      'his personality',
      'his presence',
      'his reputation',
      'his sense of comradery',
      'his sense of honor',
      'his sense of humor',
      'his sense of justice',
      'his sensitivity',
      'his suffering',
      'his sympathy',
      'his tenderness',
      'his unfortunate past',
      'his unusual alliances',
      'his unusual looks',
      'his warmth',
   ];
   var names27 = [
      'keep their distance',
      'flock towards him',
      'worship him',
      'befriend him',
      'assist him',
      'follow him',
      'welcome him',
      'welcome him with open arms',
      'invite him into their homes',
      'hit it off with him',
      'ask him for favors',
      'shower him with gifts',
      'subtly ignore him',
      'pretend to be his friend',
      'pretend to be his best friend',
      'lie about knowing him to brag',
      'brag about knowing him',
      'take pride in knowing him',
      'take pride in knowing him as a friend',
      'wish to get to know him better',
      'become his friend',
      'socialize with him',
      'try to get him to marry their off-spring',
      'buy him a drink',
      'salute him in the streets',
      'stay on his good side',
      'thank him for his service',
      'ask him to tell stories',
      'ask him about his adventures',
      'ask him about his latest victory',
      'share local gossip with him',
      'be curious about him',
      'treat him like family',
   ];
   var names28 = [
      'trying to subtlely stare',
      'secretly admiring him',
      'trying to hide from him',
      'trying to avoid him',
      'trying to please him',
      'secretly dispising him',
      'jealousy consumes them',
      'wishing they were more like him',
      'thinking of ways to become his friend',
      'wanting to fight along his side in battle',
      'hoping to one day follow in his footsteps',
      'secretly training to become more like him',
      'trying to subtly look more like him',
      'befriending his friends to get closer to him',
      'learning as much about him as possible',
      'commending him for his deeds',
      'hoping he will one day be their leader',
      'hoping their sons will grow up to be like him',
      'helping him out in any way they can',
      'awkwardly avoid talking about his past',
      'spreading rumors about him behind his back',
      'spreading stories about him',
      'making up bigger stories about him',
      "training with him whenever he's available",
      "treating him to a good meal when he's around",
   ];
   var random21 = Math.floor(Math.random() * names21.length);
   if (random21 > 3 && random21 < 9) {
      names1 = [
         'Purple',
         'Blue',
         'Green',
         'Red',
         'White',
         'Blonde',
         'Brown',
         'Light blue',
         'Light green',
         'Pink',
         'Silver',
         'Golden',
      ];
      names2 = [
         'perfectly groomed hair',
         'well groomed hair',
         'sleek hair',
         'long hair',
         'curly hair',
         'straight hair',
         'flowing hair',
         'wavy hair',
         'shoulder-length hair',
      ];
      names4 = [
         'thin',
         'chiseled',
         'craggy',
         'fine',
         'fresh',
         'full',
         'furrowed',
         'handsome',
         'sculpted',
         'strong',
         'long',
         'round',
         'bony',
         'lean',
      ];
      names7 = [
         'blue',
         'brown',
         'hazel',
         'green',
         'amber',
         'gray',
         'sapphire',
         'aquamarine',
         'pink',
         'red',
         'golden',
         'violet',
         'silver',
      ];
      names10 = [
         'village',
         'lands',
         'people',
         'town',
         'families',
         'ships',
         'armies',
         'homes',
         'castle',
         'palace',
         'natives',
         'wildlife',
         'farms',
         'country',
         'haven',
         'mountains',
         'rivers',
         'river',
         'sea',
         'woods',
         'woodlands',
         'ancestors',
         'children',
         'spirits',
      ];
      names18 = [
         'Wyninn',
         'Ninleyn',
         'Tinlef',
         'Elluin',
         'Elduin',
         'Elmon',
         'Almar',
         'Alas',
         'Alwin',
         'Almer',
         'Alre',
         'Alred',
         'Alen',
         'Alluin',
         'Alduin',
         'Almon',
         'Hagwin',
         'Hagmere',
      ];
      names19 = [
         'Moonwalker',
         'Dawnwing',
         'Dawnfury',
         'Moonfall',
         'Nightgaze',
         'Dawnthorn',
         'Stagrunner',
         'Wildoak',
         'Lunadancer',
         'Dawnwhisper',
      ];
   } else if (random21 == 10) {
      names1 = [
         'Purple',
         'Blue',
         'Green',
         'Red',
         'White',
         'Brown',
         'Light blue',
         'Light green',
         'Orange',
         'Silver',
         'Golden',
         'Yellow',
         'Black',
         'Blue',
         'Brown',
         'Hazel',
         'Black',
         'Green',
         'Amber',
         'Gray',
      ];
      names2 = [
         'short hair',
         'short hair',
         'short hair',
         'long hair',
         'curly hair',
         'straight hair',
         'sleek hair',
         'frizzy hair',
         'shaggy hair',
         'shoulder-length hair',
      ];
      names4 = [
         'thin',
         'fine',
         'fresh',
         'full',
         'handsome',
         'round',
         'bony',
         'lean',
         'skinny',
         'fat',
      ];
      names18 = [
         'Glinoflonk',
         'Bonlebick',
         'Bimbik',
         'Gnobflink',
         'Binflonk',
         'Nittlewizz',
         'Gimkink',
         'Merbibus',
         'Totonk',
         'Dinnus',
      ];
      names19 = [
         'Steambonk',
         'Berryspark',
         'Spannerwhistle',
         'Steamspanner',
         'Tosslefuse',
         'Draxlespanner',
         'Finewizzle',
         'Puddleblast',
         'Stormgauge',
         'Shinesprocket',
      ];
   } else if (random21 >= 11 || random21 < 14) {
      names2 = [
         'short hair',
         'short hair',
         'short hair',
         'long hair',
         'curly hair',
         'straight hair',
         'coily hair',
         'shaggy hair',
         'greasy hair',
         'oily hair',
         'frizzy hair',
         'shoulder-length hair',
         'dreadlocks',
      ];
      names4 = [
         'thin',
         'chiseled',
         'craggy',
         'fine',
         'fresh',
         'full',
         'furrowed',
         'strong',
         'long',
         'round',
         'bony',
         'lean',
         'skinny',
      ];
      names10 = [
         'village',
         'city',
         'lands',
         'people',
         'town',
         'families',
         'ships',
         'armies',
         'homes',
         'stronghold',
         'natives',
         'wildlife',
         'farms',
         'country',
         'haven',
         'mountains',
         'rivers',
         'river',
         'sea',
         'clan',
         'folk',
         'tribe',
         'tribes',
         'ancestors',
         'children',
         'deserts',
         'mines',
         'spirits',
      ];
      if (random21 == 11) {
         names18 = [
            'Ekon',
            'Erasto',
            'Haijen',
            'Hamedi',
            'Hokima',
            'Jaafan',
            'Jabir',
            'Jalai',
            'Javyn',
            'Jijel',
            'Juma',
            'Jumoke',
            'Kaijin',
            'Kazko',
            'Maalik',
            'Makas',
            'Malak',
            'Nyabingi',
            'Rahjin',
            'Rakash',
            'Rashi',
            'Razi',
         ];
         names19 = [
            'Xueshi',
            'Vintish',
            'Zalaahoku',
            'Valkeiki',
            'Hakjel',
            'Hanalaji',
            'Zebnanji',
            "Tesh'Rimon",
            'Junbir',
            'Zenunjo',
         ];
      } else if (random21 == 12) {
         names18 = [
            'Gnarg',
            'Gnarlug',
            'Gnorl',
            'Gnorth',
            'Gnoth',
            'Gnurl',
            'Golag',
            'Golub',
            'Gomatug',
            'Gomoku',
            'Gorgu',
            'Gorlag',
            'Grikug',
            'Grug',
            'Grukag',
            'Grukk',
            'Grung',
            'Gruul',
         ];
         names19 = [
            'Wolfbasher',
            'Burningfury',
            'Firesong',
            'Goreseeker',
            'Hellsplitter',
            'Deatheye',
            'Burninghorn',
            'Gorebasher',
            'Wolfhammer',
            'Boneslayer',
         ];
      } else if (random21 == 13) {
         names18 = [
            'Karax',
            'Baxeek',
            'Soxart',
            'Rezikmez',
            'Fizink',
            'Wimax',
            'Jexmelyx',
            'Grexmex',
            'Tinkbelex',
            'Greekeels',
         ];
         names19 = [
            'Greaseblast',
            'Haggletooth',
            'Deadnozzle',
            'Fizfingers',
            'Gearnozzle',
            'Shadowgleam',
            'Copperbuttons',
            'Deadsprocket',
            'Greasebottom',
            'Toptwister',
         ];
      }
   } else if (random21 >= 14 || random21 <= 16) {
      names2 = [
         'short hair',
         'short hair',
         'short hair',
         'long hair',
         'curly hair',
         'coily hair',
         'greasy hair',
         'shaggy hair',
         'oily hair',
         'frizzy hair',
         'shoulder-length hair',
      ];
      names4 = [
         'craggy',
         'fine',
         'fresh',
         'full',
         'furrowed',
         'strong',
         'long',
         'round',
         'fat',
      ];
      if (random21 == 14) {
         names18 = [
            'Bengahdar',
            'Banbrek',
            'Drumdus',
            'Dulgarn',
            'Galirg',
            'Kharnur',
            'Iromuador',
            'Ragorhdrom',
            'Urmbrek',
            'Theledon',
         ];
         names19 = [
            'Longmantle',
            'Highbeard',
            'Frostpike',
            'Boulderstone',
            'Bouldergem',
            'Frostshaper',
            'Bouldershout',
            'Blackaxe',
            'Goldstone',
            'Battlefist',
         ];
      }
   }
   var random1 = Math.floor(Math.random() * names1.length);
   var random2 = Math.floor(Math.random() * names2.length);
   var random3 = Math.floor(Math.random() * names3.length);
   var random4 = Math.floor(Math.random() * names4.length);
   var random5 = Math.floor(Math.random() * names5.length);
   var random6 = Math.floor(Math.random() * names6.length);
   var random7 = Math.floor(Math.random() * names7.length);
   var random8 = Math.floor(Math.random() * names8.length);
   var random9 = Math.floor(Math.random() * names9.length);
   var random10 = Math.floor(Math.random() * names10.length);
   var random11 = Math.floor(Math.random() * names11.length);
   var random12 = Math.floor(Math.random() * names12.length);
   if (random12 > 6 && random12 < 9) {
      names13 = [
         'resembling a shield',
         'resembling a sword',
         'resembling a skull',
         'resembling a flag',
         'resembling a tear',
         'of a small dragon',
         'of a small cross',
         'of a small star',
         'of a small eagle',
         'of a small swallow',
         'of a small lion',
         'of a small wolf',
         'of a small bear',
         'of a bear paw',
         'of a lion paw',
         'of an eagle claw',
         'of a talon',
         'of a dagger',
         'of a wolf paw',
         'of a shield',
         'of a sword',
         'of a skull',
         'of a flag',
         'of a tear',
         'resembling a small dragon',
         'resembling a small cross',
         'resembling a small star',
         'resembling a small eagle',
         'resembling a small swallow',
         'resembling a small lion',
         'resembling a small wolf',
         'resembling a small bear',
         'resembling a bear paw',
         'resembling a lion paw',
         'resembling an eagle claw',
         'resembling a talon',
         'resembling a dagger',
         'resembling a wolf paw',
      ];
      names14 = [
         'is almost hidden',
         'is displayed',
         'is subtly placed',
         'is prominently featured',
         'is proudly worn',
      ];
      names15 = [
         'on the right side of his neck',
         'on the left side of his neck',
         'just below his right eye',
         'just below his left eye',
         'on the side of his right cheekbone',
         'on the side of his left cheekbone',
         'on the side of the left eye',
         'on the side of his right eye',
         'just above the side of his left eye',
         'just above the side of his right eye',
         'just above the right side of his right eyebrow',
         'just above the left side of his left eyebrow',
      ];
   } else if (random12 == 9) {
      names13 = [
         'in the form of 2 stripes running from above the eyes to the bottom of the cheeks',
         'in the form of 2 stripes on each side of the face, running from just above the eyes to the bottom of the cheeks',
         'in the form of 1 stripe under his right eye',
         'in the form of 1 stripe under his left eye',
         'in the form of 2 stripes under his right eye',
         'in the form of 2 stripes under his left eye',
         'in the form of 1 stripe under each eye',
         'in the form of 1 stripe under each eye',
         'in the form of 2 stripes under each eye',
         'in the form of 2 stripes under each eye',
         'in the form of a stripe above and below his right eye',
         'in the form of a stripe above and below his left eye',
         'in the form of a stripe above and below both his eyes',
         'in the form of 1 stripe above and 2 stripes below his right eye',
         'in the form of 1 stripe above and 2 stripes below his left eye',
         'in the form of 1 stripe above and 2 stripes below both his eyes',
         'in the form of a diagonal line across his right eye',
         'in the form of a diagonal line across his left eye',
         'resembling a lightning bolt under his right eye',
         'resembling a lightning bolt under his left eye',
         'resembling a horizontal lightning bolt under his right eye',
         'resembling a horizontal lightning bolt under his left eye',
         'resembling two large lightning bolts on each side of his face',
      ];
      names14 = [
         'marks his heritage',
         'marks his ancestry',
         'marks his skills in combat',
         'marks his rank',
         'marks his upbringing',
         'marks his legacy',
         'marks his birthright',
         'marks his heirship',
         'marks his descent',
         'marks his lineage',
         'marks his blood relation',
      ];
      names15 = ['but, more importantly'];
   } else if (random12 == 10) {
      names13 = ['are spread'];
      names14 = [
         'charmingly',
         'gracefully',
         'beautifully',
         'elegantly',
         'seductively',
         'alluringly',
         'delightfully',
         'delicately',
         'graciously',
         'neatly',
         'oddly',
         'awkwardly',
         'grotesquely',
         'gracelessly',
         'unusually',
         'peculiarly',
      ];
      names15 = [
         'on his left cheek and',
         'on his right cheek and',
         'across his whole face and',
         'across his forehead and',
         'around his nose and',
         'on his neck and',
      ];
      names16 = [
         'a pleasant memory',
         'an aching memory',
         'a burning memory',
         'a stinging memory',
         'a tormenting memory',
         'a lasting burden',
         'an amusing memory',
         'a delightful memory',
         'a pleasurable memory',
         'a bittersweet memory',
         'a heartbreaking memory',
         'an agonizing memory',
         'a grievous memory',
         'a satisfying memory',
         'a fascinating memory',
         'a captivating memory',
         'an intriguing memory',
         'a compelling memory',
      ];
      names17 = [
         'his past',
         'his upbringing',
         'his fortunate upbringing',
         'his former lovers',
         'his fortunate looks',
         'his fortunate survival',
         'his luck',
         'his luck in battles',
         'his luck in love',
         'his fortunate destiny',
         'his adventurous love life',
         'his reckless luck',
         'his fortunate adventures',
         'his unfortunate upbringing',
         'his unfortunate looks',
         'his lack of luck in love',
         'his unadventurous love life',
         'his unfortunate adventures',
      ];
   } else if (random12 == 11) {
      names13 = ['are spread'];
      names14 = [
         'charmingly',
         'gracefully',
         'beautifully',
         'elegantly',
         'gorgeously',
         'handsomely',
         'seductively',
         'alluringly',
         'delightfully',
         'delicately',
         'graciously',
         'neatly',
      ];
      names15 = [
         'around his cheeks and',
         'across his whole face and',
         'across his cheeks and',
         'across his cheeks and forehead and',
         'around his nose and cheekbones and',
      ];
      names16 = [
         'a pleasant memory',
         'an amusing memory',
         'a delightful memory',
         'a gracious memory',
         'a pleasurable memory',
         'a bittersweet memory',
         'a heartbreaking memory',
         'a beautiful memory',
         'a satisfying memory',
         'a fascinating memory',
         'a captivating memory',
         'an intriguing memory',
         'a compelling memory',
      ];
      names17 = [
         'his past',
         'his upbringing',
         'his fortunate upbringing',
         'his former lovers',
         'his fortunate looks',
         'his fortunate survival',
         'his luck',
         'his luck in battles',
         'his luck in love',
         'his fortunate destiny',
         'his adventurous love life',
         'his reckless luck',
         'his fortunate adventures',
      ];
   } else if (random12 > 11) {
      names13 = [
         'charmingly',
         'gracefully',
         'beautifully',
         'elegantly',
         'gorgeously',
         'handsomely',
         'seductively',
         'alluringly',
         'delightfully',
         'graciously',
      ];
      names14 = ['compliments his'];
      names15 = [
         'eyes and',
         'cheekbones and',
         'cheeks and',
         'mouth and',
         'hair and',
         'nose and',
         'nose and mouth and',
         'eyes and mouth and',
         'eyes and cheekbones and',
         'eyes and hair and',
         'hair and cheekbones and',
      ];
      names16 = [
         'a pleasant memory',
         'an amusing memory',
         'a delightful memory',
         'a gracious memory',
         'a pleasurable memory',
         'a bittersweet memory',
         'a heartbreaking memory',
         'a beautiful memory',
         'a satisfying memory',
         'a fascinating memory',
         'a captivating memory',
         'an intriguing memory',
         'a compelling memory',
      ];
      names17 = [
         'his past',
         'his upbringing',
         'his fortunate upbringing',
         'his former lovers',
         'his fortunate looks',
         'his fortunate survival',
         'his luck',
         'his luck in battles',
         'his luck in love',
         'his fortunate destiny',
         'his adventurous love life',
         'his reckless luck',
         'his fortunate adventures',
      ];
   }
   var random13 = Math.floor(Math.random() * names13.length);
   var random14 = Math.floor(Math.random() * names14.length);
   var random15 = Math.floor(Math.random() * names15.length);
   var random16 = Math.floor(Math.random() * names16.length);
   var random17 = Math.floor(Math.random() * names17.length);
   var random20 = Math.floor(Math.random() * names20.length);
   var random22 = Math.floor(Math.random() * names22.length);
   var random23 = Math.floor(Math.random() * names23.length);
   var random24 = Math.floor(Math.random() * names24.length);
   var random25 = Math.floor(Math.random() * names25.length);
   var random26 = Math.floor(Math.random() * names26.length);
   while (random26 == random25) {
      random26 = Math.floor(Math.random() * names26.length);
   }
   var random27 = Math.floor(Math.random() * names27.length);
   var random28 = Math.floor(Math.random() * names28.length);
   var name =
      names1[random1] +
      ', ' +
      names2[random2] +
      ' ' +
      names3[random3] +
      ' a ' +
      names4[random4] +
      ', ' +
      names5[random5] +
      ' face. ' +
      names6[random6] +
      ' ' +
      names7[random7] +
      ' eyes, set ' +
      names8[random8] +
      ' within their sockets, watch ' +
      names9[random9] +
      ' over the ' +
      names10[random10] +
      " they've " +
      names11[random11] +
      ' for so long.';
   var name2 =
      names12[random12] +
      ' ' +
      names13[random13] +
      ' ' +
      names14[random14] +
      ' ' +
      names15[random15] +
      ' leaves ' +
      names16[random16] +
      ' of ' +
      names17[random17] +
      '.';
   var name3 =
      'This is the face of ' +
      stoneName +
      ', a true ' +
      names20[random20] +
      ' among ' +
      names21[random21] +
      '. He stands ' +
      names22[random22] +
      ' others, despite his ' +
      names23[random23] +
      ' frame.';
   var name4 =
      "There's something " +
      names24[random24] +
      " about him, perhaps it's " +
      names25[random25] +
      " or perhaps it's simply " +
      names26[random26] +
      '. But nonetheless, people tend to ' +
      names27[random27] +
      ', while ' +
      names28[random28] +
      '.';

   return name + '\n' + name2 + '\n' + name3 + '\n' + name4;
}
